version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ipl-db
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      # Updated path to point to your actual home directory
      context: /home/ubuntu/online-auction-system/server
    container_name: ipl-backend
    restart: always
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/auction
      - JWT_SECRET=CIPET_IPL_2026
      - ORIGIN=http://80.225.206.111:5173
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build:
      # Updated path to point to your actual home directory
      context: /home/ubuntu/online-auction-system/client
    container_name: ipl-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://80.225.206.111:3000
    depends_on:
      - backend

volumes:
  mongo_data:
